### ISSUE TITLE
Weird icon

### ISSUE THREAD

**Issue by egkoppel** [1509-online/1509-online.github.io#2]
![image](https://cloud.githubusercontent.com/assets/17106679/20461705/b2d1b608-aefd-11e6-9af0-2e0d36c20eb5.png)
Weird icon

**Comment by ZeevoX** [comment]
FIxed issue, commit #285

**Comment by ZeevoX** [comment]
Fixed issues, commit #285

**Comment by egkoppel** [comment]
OK
