### ISSUE TITLE
Drawer not working

### ISSUE THREAD

**Issue by egkoppel** [1509-online/1509-online.github.io#3]
On iOS (both Safari and Chrome) the drawer does not open when you click on the hamburger menu

> This is annoying
> Quote from The World

**Comment by ZeevoX** [comment]
`+/* START iOS Safari specific drawer workaround */
 +.demo-drawer .mdl-menu__container {
 +  z-index: -1;
 +}
 +.demo-drawer .demo-navigation {
 +  z-index: -2;
 +}
 +/* ENDOF iOS Safari specific drawer workaround */
 +`
Added this code in commit 1efe8eb74b0f044f82598db3d97f7b2780fdcf14, check it out!

**Comment by egkoppel** [comment]
It still doesn't work.
I opened this issue after I tried the fix.

**Comment by egkoppel** [comment]
I think we need to change the z index. The menu seems to be below the cards.
![img_0112](https://cloud.githubusercontent.com/assets/17106679/20465574/f284edd8-af57-11e6-9a83-927d96cd2ae0.PNG)

**Comment by egkoppel** [comment]
Converted into issue https://github.com/1509-online/1509-online.github.io/issues/4
