### ISSUE TITLE
"SIGN OUT" on /dashboard.html - no action

### ISSUE THREAD

**Issue by ZeevoX** [1509-online/1509-online.github.io#7]
The action in the card on dashboard.html has no action.

**Comment by egkoppel** [comment]
Which one?
Menu or dashboard?

**Comment by egkoppel** [comment]
Fixed

**Comment by egkoppel** [comment]
Basically, since they had the same ID the JS only added the onclick to the first one. What I did in commit 8f297d2caebf9d9b89309f24334f23fce5691b21 was to give them different IDs (`sign-out` and `sign-out-button`) and duplicate the JS code.

**Comment by ZeevoX** [comment]
Thanks!
