### ISSUE TITLE
Automatic date on new article

### ISSUE THREAD

**Issue by 1509-online** [1509-online/1509-online.github.io#9]
The date should automatically add to the article on dash_create.html

**Comment by egkoppel** [comment]
Ok

**Comment by egkoppel** [comment]
But what if it was written a while ago and we are only uploading it now.
E.g. Someone writes an article on 31/10/16 but we only upload it on 10/11/16

**Comment by ZeevoX** [comment]
It would be the date published. We should not have a need to publish outdated articles - the website is made for articles that are too time-related - e.g. Donald Trump as president. Anything that old should qualify for the magazine itself.

**Comment by egkoppel** [comment]
Ok.We can use
```javascript
var day = new Date();
var date = day.getDate() + "/" + (day.getMonth() + 1) + "/" + day.getFullYear();
```
[Documentation](http://www.w3schools.com/js/js_date_methods.asp)

**Comment by ZeevoX** [comment]
Go ahead and push it!

**Comment by egkoppel** [comment]
I haven't made it. About to do homework when I saw tons of notifications from emails about issues.
😉

**Comment by egkoppel** [comment]
DONE :smiley:
